name: splice
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11.4
  - pytorch-cuda=11.8
  - pytorch=2.0.1
  - numpy=1.25.2
  - scikit-learn
  - ipykernel
  - matplotlib=3.7.1
  - pandas
